# See https://pre-commit.com/ for usage and config

default_language_version:
  python: python3.11

exclude: ^alembic/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # general:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      # executable files:
      - id: check-executables-have-shebangs
      # other files (markup & docs):
      - id: check-json
      - id: check-yaml

#  - repo: https://github.com/pycqa/isort
#    rev: 5.12.0
#    hooks:
#      - id: isort
#
#  - repo: https://github.com/psf/black
#    rev: 23.1.0
#    hooks:
#      - id: black
